observables["Pt"]                           = dict( xlabel="p_{T}^{#gamma#gamma} (GeV)"                      , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{#gamma#gamma} (fb/GeV)"                      , rescaleLastToSecondLast=True  , name="p_{T}^{#gamma#gamma}",                            unit=" GeV",                                       legend="r", yspeed=1.0, extratext1='', extratext2='')
observables["Njets2p5"]                     = dict( xlabel="N_{jet}"                                         , ylabel=    "#Delta#sigma_{fid}/#Delta N_{jet} (fb)"                                       , rescaleLastToSecondLast=False  , name="N_{jet}",                                         unit="",                                          legend="r", yspeed=1.0, extratext1='p_{T}^{jet} > 30 GeV, |#eta^{jet}| < 2.5', extratext2='', customLabels=['0','1','2','3','>3'])
observables["AbsRapidity"]                  = dict( xlabel="|y^{#gamma#gamma}|"                              , ylabel=    "#Delta#sigma_{fid}/#Delta |y^{#gamma#gamma}| (fb)"                            , rescaleLastToSecondLast=False  , name="|y_^{#gamma#gamma}|",                              unit="",                                          legend="r", yspeed=1.0, extratext1='', extratext2='')
observables["CosThetaStar"]                 = dict( xlabel="|cos(#theta*)|"                                  , ylabel=    "#Delta#sigma_{fid}/#Delta |cos(#theta*)| (fb)"                                , rescaleLastToSecondLast=False  , name="|cos(#theta*)|",                                  unit="",                                          legend="r", yspeed=1.4, extratext1='', extratext2='')
observables["Jet2p5Pt0"]                    = dict( xlabel="p_{T}^{j_{1}} (GeV)"                             , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{j_{1}} (fb/GeV)"                             , rescaleLastToSecondLast=True  , name="p_{T}^{j_{1}}",                                   unit=" GeV",                                       legend="r", yspeed=1.0, extratext1='p_{T}^{j_{1}} > 30 GeV, |#eta^{j_{1}}| < 2.5', extratext2='')
observables["Jet2p5AbsRapidity0"]           = dict( xlabel="|y^{j_{1}}|"                                     , ylabel=    "#Delta#sigma_{fid}/#Delta |y^{j_{1}}| (fb)"                                   , rescaleLastToSecondLast=False  , name="|y^{j_{1}}|",                                     unit="",                                          legend="r", yspeed=1.5, extratext1='p_{T}^{j_{1}} > 30 GeV, |#eta^{j_{1}}| < 2.5', extratext2='')
observables["AbsDeltaPhiGgJet0Eta2p5"]      = dict( xlabel="|#Delta#phi^{#gamma#gamma,j_{1}}|"              , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#phi^{#gamma#gamma,j_{1}}| (fb)"            , rescaleLastToSecondLast=False  , name="|#Delta#phi^{#gamma#gamma,j_{1}}|",              unit="",                                          legend="r", yspeed=1.3, extratext1='p_{T}^{j_{1}} > 30 GeV, |#eta^{j_{1}}| < 2.5', extratext2='')
observables["AbsDeltaRapidityGgJet0Eta2p5"] = dict( xlabel="|#Delta y^{#gamma#gamma,j_{1}}|"                 , ylabel=    "#Delta#sigma_{fid}/#Delta |#Deltay^{#gamma#gamma,j_{1}}| (fb)"               , rescaleLastToSecondLast=True  , name="|#Delta y^{#gamma#gamma,j_{1}}|",                 unit="",                                          legend="r", yspeed=1.4, extratext1='p_{T}^{j_{1}} > 30 GeV, |#eta^{j_{1}}| < 2.5', extratext2='')
observables["Jet4p7Pt1"]                    = dict( xlabel="p_{T}^{j_{2}} (GeV)"                             , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{j_{2}} (fb/GeV)"                             , rescaleLastToSecondLast=True  , name="p_{T}^{j_{2}}",                                   unit=" GeV",                                       legend="r", yspeed=1.8, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["Jet4p7AbsRapidity1"]           = dict( xlabel="|y^{j_{2}}|"                                     , ylabel=    "#Delta#sigma_{fid}/#Delta |y^{j_{2}}| (fb)"                                   , rescaleLastToSecondLast=False  , name="|y^{j_{2}}|",                                     unit="",                                          legend="r", yspeed=1.55, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["AbsDeltaPhiJjEta4p7"]          = dict( xlabel="|#Delta#phi^{j_{1},j_{2}}|"                     , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#phi^{j_{1},j_{2}}| (fb)"                   , rescaleLastToSecondLast=False  , name="|#Delta#phi^{j_{1},j_{2}}|",                     unit="",                                          legend="r", yspeed=1.35, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["AbsDeltaPhiGgJjEta4p7"]        = dict( xlabel="|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|"         , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#phi^{#gamma#gamma,j_{1}j_{2}}| (fb)"       , rescaleLastToSecondLast=False  , name="|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|",         unit="",                                          legend="r", yspeed=1.0, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["ZeppenfeldEta4p7"]             = dict( xlabel="|#bar{#eta}^{j_{1}j_{2}} - #eta^{#gamma#gamma}|" , ylabel=    "#Delta#sigma_{fid}/#Delta |#bar{#eta}^{j_{1}j_{2}} - #eta^{#gamma#gamma}| (fb)", rescaleLastToSecondLast=True , name="|#bar{#eta}^{j_{1}j_{2}} - #eta^{#gamma#gamma}|", unit="",                                          legend="r", yspeed=1.7, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["MjjEta4p7"]                    = dict( xlabel="m^{j_{1}j_{2}} (GeV)"                            , ylabel=    "#Delta#sigma_{fid}/#Delta m^{j_{1}j_{2}} (fb/GeV)"                            , rescaleLastToSecondLast=True  , name="m^{j_{1}j_{2}}",                                  unit=" GeV",                                       legend="r", yspeed=1.5, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["AbsDeltaEtaJJEta4p7"]          = dict( xlabel="|#Delta#eta^{j_{1},j_{2}}|"                     , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#eta^{j_{1},j_{2}}| (fb)"                   , rescaleLastToSecondLast=True  , name="|#Delta#eta^{j_{1},j_{2}}|",                     unit="",                                          legend="r", yspeed=1.5, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='')
observables["Jet4p7Pt1VBFlike"]             = dict( xlabel="p_{T}^{j_{2}} (GeV)"                             , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{j_{2}} (fb/GeV)"                             , rescaleLastToSecondLast=True  , name="p_{T}^{j_{2}}",                                   unit=" GeV",                                       legend="r", yspeed=1.8, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='m^{j_{1}j_{2}} > 200 GeV, |#Delta#eta^{j_{1}j_{2}}| > 3.5')
observables["AbsDeltaPhiJjEta4p7VBFlike"]   = dict( xlabel="|#Delta#phi^{j_{1},j_{2}}|"                     , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#phi^{j_{1},j_{2}}| (fb)"                   , rescaleLastToSecondLast=False  , name="|#Delta#phi^{j_{1},j_{2}}|",                     unit="",                                          legend="r", yspeed=2.0, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='m^{j_{1}j_{2}} > 200 GeV, |#Delta#eta^{j_{1}j_{2}}| > 3.5')
observables["AbsDeltaPhiGgJjEta4p7VBFlike"] = dict( xlabel="|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|"         , ylabel=    "#Delta#sigma_{fid}/#Delta |#Delta#phi^{#gamma#gamma,j_{1}j_{2}}| (fb)"       , rescaleLastToSecondLast=False  , name="|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|",         unit="",                                          legend="r", yspeed=1.0, extratext1='p_{T}^{j_{1,2}} > 30 GeV, |#eta^{j_{1,2}}| < 4.7', extratext2='m^{j_{1}j_{2}} > 200 GeV, |#Delta#eta^{j_{1}j_{2}}| > 3.5')
observables["PtNjets2p5_0"]                 = dict( xlabel="p_{T}^{#gamma#gamma}, N_{jet}=0 (GeV)"           , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{#gamma#gamma}, N_{jet}=0 (fb/GeV)"           , rescaleLastToSecondLast=True  , name="p_{T}^{#gamma#gamma}",                            unit=" GeV",                                       legend="r", yspeed=1.0, extratext1='p_{T}^{jet} > 30 GeV, |#eta^{jet}| < 2.5', extratext2='')
observables["PtNjets2p5_1"]                 = dict( xlabel="p_{T}^{#gamma#gamma}, N_{jet}=1 (GeV)"           , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{#gamma#gamma}, N_{jet}=1 (fb/Gev)"           , rescaleLastToSecondLast=True  , name="p_{T}^{#gamma#gamma}",                            unit=" GeV",                                       legend="r", yspeed=0.7, extratext1='p_{T}^{jet} > 30 GeV, |#eta^{jet}| < 2.5', extratext2='')
observables["PtNjets2p5_1plus"]             = dict( xlabel="p_{T}^{#gamma#gamma}, N_{jet}>1 (GeV)"           , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{#gamma#gamma}, N_{jet}>1 (fb/GeV)"           , rescaleLastToSecondLast=True  , name="p_{T}^{#gamma#gamma}",                            unit=" GeV",                                       legend="r", yspeed=0.7, extratext1='p_{T}^{jet} > 30 GeV, |#eta^{jet}| < 2.5', extratext2='')
observables["MET"]                          = dict( xlabel="p_{T}^{miss} (GeV)"                              , ylabel=    "#Delta#sigma_{fid}/#Delta p_{T}^{miss} (fb/GeV)"                              , rescaleLastToSecondLast=True  , name="p_{T}^{miss}",                                    unit=" GeV",                                       legend="r", yspeed=1.0, extratext1='', extratext2='')
observables["NjetsBflavorTight2p5"]         = dict( xlabel="N_{jet}^{b}"                                     , ylabel=    "#Delta#sigma_{fid}/#Delta N_{jet}^{b} (fb)"                                   , rescaleLastToSecondLast=False  , name="N_{jet}^{b}",                                     unit="",                                          legend="r", yspeed=1.0, extratext1='p_{T}^{jet} > 30 GeV, |#eta^{jet}| < 2.5', extratext2='', customLabels=['0','1','>1'])
observables["Nleptons"]                     = dict( xlabel="N_{lepton}"                                      , ylabel=    "#Delta#sigma_{fid}/#Delta N_{lepton} (fb)"                                    , rescaleLastToSecondLast=False  , name="N_{lepton}",                                      unit="",                                          legend="r", yspeed=1.0, extratext1='', extratext2='', customLabels=['0','1','>1'])
observables["1Lepton1Bjet"]                 = dict( xlabel="#geq 1 lepton, #geq 1 b"                       , ylabel=    "#sigma_{fid}(N_{lepton} = 1, N_{b} = 1 (fb)"                       , rescaleLastToSecondLast=True  , name="N_{lepton} = 1, N_{b} = 1",                       unit="",                                          legend="r", yspeed=1.0, extratext1='', extratext2='')
observables["1LeptonHighMET"]               = dict( xlabel="1-lepton, high-p_{T}^{miss}"               , ylabel=    "#sigma_{fid}(N_{lepton} = 1, high p_{T}^{miss} (fb)"               , rescaleLastToSecondLast=True  , name="N_{lepton} = 1, high-p_{T}^{miss}",               unit="",                                          legend="r", yspeed=1.0, extratext1='', extratext2='')
observables["1LeptonLowMET"]                = dict( xlabel="1-lepton, low-p_{T}^{miss}"                , ylabel=    "#sigma_{fid}(N_{lepton} = 1, low p_{T}^{miss} (fb)"                , rescaleLastToSecondLast=True  , name="N_{lepton} = 1, low-p_{T}^{miss}",                unit="",                                          legend="r", yspeed=1.0, extratext1='', extratext2='')



'Pt'                           : 'p_{T}^{#gamma#gamma} (GeV)',
'Njets2p5'                     : 'N_{jet}',
'AbsRapidity'                  : '|y^{#gamma#gamma}|',
'CosThetaStar'                 : '|cos(#theta*)|',
'Jet2p5Pt0'                    : 'p_{T}^{j_{1}} (GeV)',
'Jet2p5AbsRapidity0'           : '|y^{j_{1}}|',
'AbsDeltaPhiGgJet0Eta2p5'      : '|#Delta#phi^{#gamma#gamma,j_{1}}|',
'AbsDeltaRapidityGgJet0Eta2p5' : '|#Delta y^{#gamma#gamma,j_{1}}|',
'Jet4p7Pt1'                    : 'p_{T}^{j_{2}} (GeV)',
'Jet4p7AbsRapidity1'           : '|y^{j_{2}}|',
'AbsDeltaPhiJjEta4p7'          : '|#Delta#phi^{j_{1},j_{2}}|',
'AbsDeltaPhiGgJjEta4p7'        : '|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|',
'ZeppenfeldEta4p7'             : '|#bar{#eta}^{j_{1}j_{2}} - #eta^{#gamma#gamma}|',
'MjjEta4p7'                    : 'm^{j_{1}j_{2}} (GeV)',
'AbsDeltaEtaJJEta4p7'          : '|#Delta#eta^{j_{1},j_{2}}|',
'Jet4p7Pt1VBFlike'             : 'p_{T}^{j_{2}} (GeV)',
'AbsDeltaPhiJjEta4p7VBFlike'   : '|#Delta#phi^{j_{1},j_{2}}|',
'AbsDeltaPhiGgJjEta4p7VBFlike' : '|#Delta#phi^{#gamma#gamma,j_{1}j_{2}}|',
'PtNjets2p5_0'                 : 'p_{T}^{#gamma#gamma}, N_{jet}=0 (GeV)',
'PtNjets2p5_1'                 : 'p_{T}^{#gamma#gamma}, N_{jet}=1 (GeV)',
'PtNjets2p5_1plus'             : 'p_{T}^{#gamma#gamma}, N_{jet}>1 (GeV)',
'MET'                          : 'p_{T}^{miss} (GeV)',
'NjetsBflavorTight2p5'         : 'N_{jet}^{b}',
'Nleptons'                     : 'N_{lepton}',
'1Lepton1Bjet'                 : '#geq 1 lepton, #geq 1 b',
'1LeptonHighMET'               : '1-lepton, high-p_{T}^{miss}',
'1LeptonLowMET'                : '1-lepton, low-p_{T}^{miss}',
