#!/bin/bash
COMMANDLINE="$*"
mkdir -p bkglogs
TIMESTAMP=`date '+%Y-%m-%d-%H%M%S'`

name="bkglogs/bkg_${TIMESTAMP}"
if [[ -e $name.log ]] ; then
    i=0
    while [[ -e $name-$i.log ]] ; do
        let i++
    done
    name=$name-$i
fi

LOGFILE="$name.log"
# nohup $COMMANDLINE </dev/null >command.log 2>&1 &
nohup $COMMANDLINE </dev/null >$LOGFILE 2>&1 &
pid=$!
echo "$pid : $LOGFILE : $COMMANDLINE" >> bkglogs/pids.txt
echo $pid